# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://yongqiangyang.github.io/
date_format: "ordinal"
title: 个人博客
subtitle: "这是某人的个人博客"
description: "杨永强的个人博客"
keywords: yangyongqiang,
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Yongqiang Yang
organization:
organization_url:
github_username: yongqiangyang
location: NanJing, China
email: yyq@nuaa.edu.cn

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

  # -
  #   href: /wiki/
  #   label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /contact/
    label: 联系

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: yongqiangyang/yongqiangyang.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username:
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: yangyongqiang
    repo: blog-comments
    oauth:
        client_id: c6330b5052137a20c448
        client_secret: 93900c57d6ba2c8a34771776619b759e89b7705f
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: yangyongqiang
    repo: blog-comments
    clientID: c6330b5052137a20c448
    clientSecret: 93900c57d6ba2c8a34771776619b759e89b7705f
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-140015679-1
